CE103 Algorithms and Programming I HW3: FileOperation.FileUtility Class Reference
FileOperation.FileUtility Class Reference
Static Public Member Functions
static byte[] ReadBlock (int count, int blocksize, string path)
static bool AppendBlock (byte[] data, string path)
static bool AppendBlock2 (byte[] data, string path)
static bool UpdateBlock (byte[] data, int count, int blocksize, string path)
static bool DeleteBlock (int count, int blocksize, string path)
Member Function Documentation
AppendBlock()
static bool FileOperation.FileUtility.AppendBlock (byte[] data, string path) inline static
Referenced by Main.MainScreen.AddBook().
AppendBlock2()
static bool FileOperation.FileUtility.AppendBlock2 (byte[] data, string path) inline static
Referenced by Main.MainScreen.AddBook2().
DeleteBlock()
static bool FileOperation.FileUtility.DeleteBlock (int count, int blocksize, string path) inline static
Referenced by library_manager_app.Program1.Main().
ReadBlock()
static byte[] FileOperation.FileUtility.ReadBlock (int count, int blocksize, string path) inline static
Referenced by library_manager_app.Program1.Main(), and Main.MainScreen.PullBook().
UpdateBlock()
static bool FileOperation.FileUtility.UpdateBlock (byte[] data, int count, int blocksize, string path) inline static
The documentation for this class was generated from the following file:
C:/Users/gokay/do/ce103-hw3-gokay-dervisoglu/library-manager-dll/FileUtility.cs