CE103 Algorithms and Programming I HW3: LibraryManagement.ConversionUtility Class Reference
LibraryManagement.ConversionUtility Class Reference
Static Public Member Functions
static byte[] ToByte (this string hexString)
static string ToHex (this byte[] arr)
static bool IsHex (this string str)
static int GetInt (this byte[] data, int offset, int length)
static string ToAscii (this string hexString)
static int ByteArrayToInteger (byte[] byteArray)
static byte[] IntegerToByteArray (int value)
static byte[] StringToByteArray (string data)
static string ByteArrayToString (byte[] byteArray)
Member Function Documentation
ByteArrayToInteger()
static int LibraryManagement.ConversionUtility.ByteArrayToInteger (byte[] byteArray) inline static
Referenced by Bookfeatures.BookFeature.ByteArrayBlockToBook().
ByteArrayToString()
static string LibraryManagement.ConversionUtility.ByteArrayToString (byte[] byteArray) inline static
Referenced by Bookfeatures.BookFeature.ByteArrayBlockToBook().
GetInt()
static int LibraryManagement.ConversionUtility.GetInt (this byte[] data, int offset, int length) inline static
IntegerToByteArray()
static byte[] LibraryManagement.ConversionUtility.IntegerToByteArray (int value) inline static
Referenced by Bookfeatures.BookFeature.BookToByteArrayBlock().
IsHex()
static bool LibraryManagement.ConversionUtility.IsHex (this string str) inline static
StringToByteArray()
static byte[] LibraryManagement.ConversionUtility.StringToByteArray (string data) inline static
Referenced by Bookfeatures.BookFeature.BookToByteArrayBlock().
ToAscii()
static string LibraryManagement.ConversionUtility.ToAscii (this string hexString) inline static
ToByte()
static byte[] LibraryManagement.ConversionUtility.ToByte (this string hexString) inline static
ToHex()
static string LibraryManagement.ConversionUtility.ToHex (this byte[] arr) inline static
The documentation for this class was generated from the following file:
C:/Users/gokay/do/ce103-hw3-gokay-dervisoglu/library-manager-dll/ConversionUtility.cs