CE103 Algorithms and Programming I HW3: Main.MainScreen Class Reference
Main.MainScreen Class Reference
Public Member Functions
void ControlFile (string path, string filename)
void AddBook (int Id, string Title, string Description, string Authors, string Categories, int Years, int Pages, string City, int Edition, string Editors, string Publishers, string Url, int Doi, int Isbn, int Price, string Rack, string Row)
void AddBook2 (int id, string title, string description, string authors, string categories, int years, int pages, string city, int edition, string editors, string publishers, string url, int doi, int isbn, int price, string rack, string row)
void PullBook ()
Member Function Documentation
AddBook()
void Main.MainScreen.AddBook (int Id, string Title, string Description, string Authors, string Categories, int Years, int Pages, string City, int Edition, string Editors, string Publishers, string Url, int Doi, int Isbn, int Price, string Rack, string Row) inline
References FileOperation.FileUtility.AppendBlock(), Bookfeatures.BookFeature.BookToByteArrayBlock(), Bookfeatures.BookFeature.City, Bookfeatures.BookFeature.DOI, Bookfeatures.BookFeature.ISBN, Bookfeatures.BookFeature.Rack, Bookfeatures.BookFeature.Row, and Bookfeatures.BookFeature.URL.
Referenced by library_manager_app.Program1.Main().
AddBook2()
void Main.MainScreen.AddBook2 (int id, string title, string description, string authors, string categories, int years, int pages, string city, int edition, string editors, string publishers, string url, int doi, int isbn, int price, string rack, string row) inline
References FileOperation.FileUtility.AppendBlock2(), Bookfeatures.BookFeature.BookToByteArrayBlock(), Bookfeatures.BookFeature.City, Bookfeatures.BookFeature.DOI, Bookfeatures.BookFeature.ISBN, Bookfeatures.BookFeature.Rack, Bookfeatures.BookFeature.Row, and Bookfeatures.BookFeature.URL.
ControlFile()
void Main.MainScreen.ControlFile (string path, string filename) inline
PullBook()
void Main.MainScreen.PullBook () inline
References Bookfeatures.BookFeature.BOOK_DATA_BLOCK_SIZE, Bookfeatures.BookFeature.ByteArrayBlockToBook(), and FileOperation.FileUtility.ReadBlock().
The documentation for this class was generated from the following file:
C:/Users/gokay/do/ce103-hw3-gokay-dervisoglu/library-manager-dll/MainScreen.cs